apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bakehouse
  name: bakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakehouse
  template:
    metadata:
      labels:
        app: bakehouse
    spec:
      containers:
      - image: yassmin970/bakehouseyassmin:v${BUILD_NUMBER}-${BRANCH_NAME}
        name: bakehouse
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
